---
- name: first play
  hosts: poc-mysql
  tasks:
    - name: Dump all databases to hostname.sql
      mysql_db:
        state: dump
        name: all
        target: /tmp/dump-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}.sql 
       
